# Set to true to disable the Grype image scan completely
disabled: false

ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    reason: "No fixes to glob npm available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: CVE-2025-60876
    reason: "No fixes to busybox apk available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: CVE-2026-22184
    reason: "No fixes to zlib apk available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: GHSA-34x7-hfp2-rc4v
    reason: "tar is bundled inside npm, not used at runtime. ISPA never extracts tar archives. No fix available in base image npm."
  - vulnerability: GHSA-r6q2-hw4h-h46w
    reason: "tar is bundled inside npm, not used at runtime. ISPA never extracts tar archives. No fix available in base image npm."
  - vulnerability: GHSA-8qq5-rm4j-mr97
    reason: "tar is bundled inside npm, not used at runtime. ISPA never extracts tar archives. No fix available in base image npm."

# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
